### ISSUE TITLE
Does not show in modules list in admin panel

### ISSUE THREAD

**Issue by Censtudios** [plantoschka/humhub-modules-reputation#1]
I uploaded this into protected/modules/reputation but it doesn't show up in the admin panel. So I am unable to install this...

Is it because it's missing config.php?

Is there another way to install this?

**Comment by mariobrussi** [comment]
+1

**Comment by plantoschka** [comment]
Which version of HumHub are you using?
This module will only work with 0.11.*

I should mention this in the Readme.

**Comment by Censtudios** [comment]
Oh I'm using 1.0 beta2.

The latest stable version is 0.20. If possible you should probably make this module compatible with that version :D It looks like a really good module with great potential

**Comment by mariobrussi** [comment]
i'm using the latest beta (1.1.0-beta.1) and i'm really interested in this module, can you provide a guide to allow it usage?

**Comment by Buliwyfa** [comment]
+1

**Comment by plantoschka** [comment]
I hope I find some time in the coming weeks to port this to the newest HumHub Version.

**Comment by Buliwyfa** [comment]
If you got time I would like to hire to dev another module... contac me ;)

**Comment by randomboygh** [comment]
Great module!
Waiting for update

**Comment by globeFrEak** [comment]
Hi, i have it ported for Humhub 1.1 .
You can find it in my Repo - https://github.com/globeFrEak/humhub-modules-reputation
Please test it and report me founded bugs.

**Comment by plantoschka** [comment]
Great ! Really appreciate it.

**Comment by randomboygh** [comment]
@globeFrEak Just tested. Works good. Thanks
