### ISSUE TITLE
Frage: Portierung auf Yii2

### ISSUE THREAD

**Issue by globeFrEak** [plantoschka/humhub-modules-reputation#2]
Hallo Anton,
ist eine Portierung deines Modules auf Yii2 (Humhub >0.20 oder >1.0) geplant?
Grüße Philipp

**Comment by plantoschka** [comment]
Hallo,

momentan nicht. Mir fehlt leider die Zeit.

Viele Grüße
Anton

**Comment by globeFrEak** [comment]
Darf ich deinen Code zur Konvertierung nutzen - sofern ich das hinbekommen sollte :-P

**Comment by plantoschka** [comment]
Würde mich freuen, wenn es jmd. portiert.
